version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodbhost:27017/blog
    depends_on:
      - mongodbhost


  mongodbhost:
    image: mongo:latest
    ports:
      - "27019:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
